# Generated by Django 5.2 on 2025-04-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
