# Generated by Django 5.2 on 2025-04-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_post_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="creation_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Original creation time extracted from image metadata",
                null=True,
            ),
        ),
    ]
