# Generated by Django 5.2 on 2025-04-22 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_post_creation_time"),
        ("shop", "0002_agent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="creation_time",
        ),
        migrations.CreateModel(
            name="PostAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="posts/")),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="shop.agent",
                    ),
                ),
            ],
        ),
    ]
