# Generated by Django 5.2 on 2025-04-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_remove_post_creation_time_postagent"),
    ]

    operations = [
        migrations.AddField(
            model_name="postagent",
            name="document",
            field=models.FileField(
                blank=True, null=True, upload_to="documents/%Y/%m/%d/"
            ),
        ),
    ]
