# Generated by Django 5.2 on 2025-04-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0005_postagent_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="document",
            field=models.FileField(
                blank=True, null=True, upload_to="documents/%Y/%m/%d/"
            ),
        ),
    ]
