# Generated by Django 5.2 on 2025-05-01 12:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="Description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="Region",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shop",
            name="manager_name",
            field=models.CharField(default="admin", max_length=255),
            preserve_default=False,
        ),
    ]
